language: go
go:
  - 1.13
  - 1.14

script:
  - make test
  - go build ./...

after_success:
  - make cover
  - bash <(curl -s https://codecov.io/bash)

notifications:
  on_success: never
  on_failure: always
